on:
  workflow_dispatch:

jobs:
  compile:
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"
          libraries: |
            - name: LiquidCrystal
